<a href="https://colab.research.google.com/github/nurfnick/Numerical_Methods/blob/master/ProjectPart4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project Part 4



I don't need lots of the pieces from earlier assignments so I will not include them here.

In [2]:
import math
import numpy as np

## Gauss-Jordan Method

The Gauss-Jordan elimination method is all about solving linear systems of equations.  Something of the form
$$
\left\{
\begin{align}
a_{1,1} x_1 +&\dots a_{1,n} x_n = y_1\\
&\vdots\\
a_{n,1}x_1+&\dots a_{n,n} x_n = y_n
\end{align}
\right.
$$

First thing we need to figure out is how to create an augmented matrix from this!

$$
\left[
\begin{array}{ccc|c}
a_{1,1} & \dots & a_{1,n} & y_1\\
\vdots&\ddots&\vdots&\vdots\\
a_{n,1} &\dots& a_{n,n}&y_n
\end{array}
\right]
$$
And how to deal with this matrix!

In [3]:
A = np.array([[1,2,3],[2,3,4]])

A

array([[1, 2, 3],
       [2, 3, 4]])

In [4]:
def addRows(matrix,targetRow, modifierRow, value):
  newRow = matrix[targetRow,:]+value*matrix[modifierRow,:]
  newMatrix = []
  for i in range(len(matrix)):
    if i != targetRow:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(newRow)
  return np.array(newMatrix)



In [5]:
addRows(A,0,1,10)

array([[21, 32, 43],
       [ 2,  3,  4]])

In [6]:
def swapRows(matrix,row1,row2):
  newMatrix = []
  for i in range(len(matrix)):
    if i == row1:
      newMatrix.append(matrix[row2,:])
    elif i == row2:
      newMatrix.append(matrix[row1,:])
    else:
      newMatrix.append(matrix[i,:])
  return np.array(newMatrix)



In [7]:
swapRows(A,0,1)

array([[2, 3, 4],
       [1, 2, 3]])

In [8]:
def changeToLeadingOne(matrix,row,column):
  newMatrix =[]
  for i in range(len(matrix)):
    if i != row:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(1/matrix[row,column]*matrix[row,:])
  return np.array(newMatrix)


In [9]:
changeToLeadingOne(A,1,0)

array([[1. , 2. , 3. ],
       [1. , 1.5, 2. ]])

In [10]:
def gaussJordan(matrix):
  newMatrix = matrix
  for pivot in range(len(matrix)):
    newMatrix = changeToLeadingOne(newMatrix,pivot,pivot)
    for column in range(0,pivot):
      newMatrix = addRows(newMatrix,column,pivot,-newMatrix[column,pivot])
    for column in range(pivot+1,len(matrix)):
      newMatrix = addRows(newMatrix,column,pivot,-newMatrix[column,pivot])
  return newMatrix


In [11]:
gaussJordan(A)

array([[ 1.,  0., -1.],
       [-0.,  1.,  2.]])

Let's try that again with a little more complicated matrix!

In [12]:
B = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [13]:
gaussJordan(B)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in multiply
  import sys


array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

Oh no!  What happened!  Let's follow the process and see where it went wrong.

First we already have a leading 1 so I will somplify the other two

In [14]:
B = addRows(B,1,0,-2)
B

array([[ 1,  2,  3,  4],
       [ 0, -1, -2, -3],
       [ 3,  4,  5,  6]])

In [15]:
B = addRows(B,2,0,-3)
B

array([[ 1,  2,  3,  4],
       [ 0, -1, -2, -3],
       [ 0, -2, -4, -6]])

In [16]:
B = changeToLeadingOne(B,1,1)
B

array([[ 1.,  2.,  3.,  4.],
       [-0.,  1.,  2.,  3.],
       [ 0., -2., -4., -6.]])

New leading one, what could go wrong!

In [17]:
B = addRows(B,0,1,-2)
B

array([[ 1.,  0., -1., -2.],
       [-0.,  1.,  2.,  3.],
       [ 0., -2., -4., -6.]])

In [18]:
addRows(B,2,1,2)

array([[ 1.,  0., -1., -2.],
       [-0.,  1.,  2.,  3.],
       [ 0.,  0.,  0.,  0.]])

Here is the issue!  I get a full compliment of zeros.  While this system is still solvable, my method will fail because I cannot find another pivot (leading 1)  By the way the solution here is that
$$
\begin{align}
x &= -2+t\\
y &= 3-2t\\
z &= t
\end{align}
$$

$z$ the third variable can be what ever it wants but that determines what the rest must me.

##Computing Inverses

I am curious if I can get my algorithm to compute a matrix inverse.  The traditional method to doing this is to take your original square matrix and augment the identity matrix, then preform row ops until you ge the inverse.
$$
\left[A|I\right] \to \left[I|A^{-1}\right]
$$

Let's try it on 
$$
A=\left[
\begin{array}{cc}
1&2\\
3&4
\end{array}
\right]
$$


In [20]:
C = np.array([[1,2,1,0],[3,4,0,1]])

In [21]:
gaussJordan(C)

array([[ 1. ,  0. , -2. ,  1. ],
       [-0. ,  1. ,  1.5, -0.5]])

So I think $A^{-1}$ is
$$
A^{-1}=\left[
\begin{array}{cc}
-2&1\\
1.5&-\frac12
\end{array}
\right]
$$
Let's make python check it.  To multiply matricies you use the @ symbol

In [23]:
Ainverse = np.array([[-2,1],[1.5,-.5]])
Anew = np.array([[1,2],[3,4]])

In [24]:
Anew @ Ainverse

array([[1., 0.],
       [0., 1.]])

Sweet!

##Using Some Packages in Python

I haven't used this package yet but scipy is for doing scientific computing in python.  Many of the programs we have created are premade in the scipy package

In [26]:
import scipy.linalg as la

la.inv(Anew)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
la.solve(A[:,:2],A[:,2])#Using the original A giving it the coeffiecient and then the solutions.

array([-1.,  2.])