<a href="https://colab.research.google.com/github/nurfnick/Numerical_Methods/blob/master/Module_4_Guass_Jordan_Elimination/Cholesky.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Cholesky Decomposition

The Cholesky decomposition is a decomposition of a Hermitian, positive-definite matrix into the product of a lower triangular matrix and its conjugate transpose. This is an efficient method for solving systems of linear equations and is commonly used in Monte Carlo simulations, Kalman filters, and optimizing certain mathematical functions.

In [1]:
import numpy as np

def cholesky_decomposition(A):
    """
    Computes the Cholesky decomposition of a symmetric positive definite matrix.

    Parameters:
    A (numpy.ndarray): A symmetric positive definite matrix.

    Returns:
    numpy.ndarray: The lower triangular matrix L such that A = L @ L.T

    Raises:
    ValueError: If the input matrix is not square.
    np.linalg.LinAlgError: If the matrix is not positive definite.
    """
    n = A.shape[0]

    if A.shape[1] != n:
        raise ValueError("Input matrix must be square.")

    L = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1):
            if i == j:
                # Diagonal elements
                sum_val = np.sum(L[i, :j]**2)
                # Check for positive definiteness
                if A[i, i] - sum_val <= 0:
                    raise np.linalg.LinAlgError("Matrix is not positive definite.")
                L[i, j] = np.sqrt(A[i, i] - sum_val)
            else:
                # Off-diagonal elements
                sum_val = np.sum(L[i, :j] * L[j, :j])
                # Check for division by zero, which implies non-positive definiteness
                if L[j, j] == 0:
                    raise np.linalg.LinAlgError("Matrix is not positive definite (zero on diagonal of L).")
                L[i, j] = (A[i, j] - sum_val) / L[j, j]
    return L


In [2]:
# Example usage:
# A symmetric positive definite matrix
A = np.array([
    [4, 12, -16],
    [12, 37, -43],
    [-16, -43, 98]
], dtype=float)

print("Original Matrix A:")
print(A)

try:
    L = cholesky_decomposition(A)
    print("\nLower triangular matrix L (Cholesky decomposition):")
    print(L)

    # Verify the decomposition: A = L @ L.T
    A_reconstructed = L @ L.T
    print("\nReconstructed Matrix (L @ L.T):")
    print(A_reconstructed)

    # Check if A_reconstructed is close to A
    print("\nIs A_reconstructed close to A?", np.allclose(A, A_reconstructed))

except ValueError as e:
    print(f"Error: {e}")
except np.linalg.LinAlgError as e:
    print(f"Error: {e}")


Original Matrix A:
[[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]

Lower triangular matrix L (Cholesky decomposition):
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]

Reconstructed Matrix (L @ L.T):
[[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]

Is A_reconstructed close to A? True


In [4]:
A = np.array([
    [9, 3, 6],
    [3, 5, 1],
    [6, 1, 9]
], dtype=float)

In [6]:
L = cholesky_decomposition(A)
print(L)

[[ 3.          0.          0.        ]
 [ 1.          2.          0.        ]
 [ 2.         -0.5         2.17944947]]
